import {test,expect} from '@playwright/test'

test('asset directory searches source inventory without changing the project or loading models',async({page})=>{
  const requests=[]
  page.on('request',r=>requests.push(r.url()))
  await page.goto('/')
  await expect.poll(()=>page.evaluate(()=>localStorage.getItem('insta-studio-v2'))).not.toBeNull()
  const before=await page.evaluate(()=>localStorage.getItem('insta-studio-v2'))
  const entry=page.getByRole('button',{name:'查看90项资产目录',exact:true})
  await expect(entry).toBeVisible()
  await entry.click()
  const panel=page.getByRole('region',{name:'SU资产目录',exact:true})
  await expect(panel).toContainText('90 项资产')
  await expect(panel.locator('article')).toHaveCount(90)
  await page.getByLabel('资产接入状态').selectOption('ready')
  await expect(panel.locator('article')).toHaveCount(4)
  await page.getByLabel('资产接入状态').selectOption('pending')
  await expect(panel.locator('article')).toHaveCount(86)
  await page.getByLabel('资产编号或名称').fill(' ASSET-316267 ')
  await expect(panel.locator('article')).toHaveCount(1)
  await expect(panel).toContainText('SI 未确认')
  await expect(panel).toContainText('未接入网页')
  await expect(panel.getByRole('button',{name:/加入|放置/})).toHaveCount(0)
  expect(await page.evaluate(()=>localStorage.getItem('insta-studio-v2'))).toBe(before)
  expect(requests.some(url=>/\.glb|\.skp|\.dae/.test(url))).toBe(false)
  await page.getByLabel('资产编号或名称').fill('不存在')
  await expect(panel).toContainText('没有匹配资产')
  await page.getByRole('button',{name:'关闭资产目录',exact:true}).click()
  await expect(panel).toHaveCount(0)
})

test('asset directory category filter fits narrow screens',async({page})=>{
  await page.setViewportSize({width:390,height:844})
  await page.goto('/')
  await expect(page.getByRole('button',{name:'查看90项资产目录',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'查看90项资产目录',exact:true}).click()
  await page.getByLabel('资产类别').selectOption('体验桌')
  const panel=page.getByRole('region',{name:'SU资产目录',exact:true})
  await expect(panel.locator('article')).toHaveCount(5)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})
