import {test,expect} from '@playwright/test'

test('case library separates reference purposes and SI evidence without changing the project',async({page})=>{
  await page.goto('/')
  await expect.poll(()=>page.evaluate(async()=>(await (await import('/src/project-db.js')).readProjectRaw()))).not.toBeNull()
  const before=await page.evaluate(async()=>(await (await import('/src/project-db.js')).readProjectRaw()))
  await page.getByRole('button',{name:'查看五店案例证据'}).click({timeout:5000})
  await expect(page.locator('.case-card')).toHaveCount(5)
  await expect(page.locator('.case-library')).toContainText('不是完整几何')
  await page.getByLabel('案例 SI 筛选').selectOption('SI1.0')
  await expect(page.locator('.case-card')).toHaveCount(2)
  const kunshan=page.locator('.case-card').filter({hasText:'昆山'})
  await expect(kunshan).toContainText('800')
  await expect(kunshan).toContainText('1000')
  await expect(kunshan).toContainText('第 5 页')
  await page.getByLabel('案例用途').selectOption('render')
  await expect(kunshan.locator('.case-reference')).toHaveCount(3)
  await expect(kunshan).toContainText('同相机')
  await page.getByLabel('案例用途').selectOption('layout')
  await expect(kunshan.locator('.case-reference')).toHaveCount(3)
  await expect(kunshan).toContainText('家具定位')
  expect(await page.evaluate(async()=>(await (await import('/src/project-db.js')).readProjectRaw()))).toBe(before)
  await page.setViewportSize({width:390,height:900})
  await kunshan.getByText('源文件与追溯记录',{exact:true}).click()
  await kunshan.locator('.case-reference summary').first().click()
  expect(await page.evaluate(async()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(391)
  await kunshan.screenshot({path:'test-results/case-library-mobile.png'})
  await page.getByRole('button',{name:'关闭案例证据'}).click()
  await expect(page.locator('.case-library')).toHaveCount(0)
})
