import {test,expect} from '@playwright/test'
import {dimensions,generatePlans,issues} from '../src/layout.js'
test('dimensions and candidate bounds',()=>{
 expect(dimensions('area',0,0,48,1,3).w**2).toBeCloseTo(48)
 expect(()=>dimensions('dimensions',0,6,0,1,3)).toThrow()
 for(const w of [4,8,30])for(const d of [4,6,30]){const plans=generatePlans({w,d,h:3});expect(plans).toHaveLength(4);for(const p of plans)expect(issues(p)).toEqual([])}
})
test('input, four cards, editing, white model, both styles, persistence',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/');await expect(page.getByRole('heading',{name:'从空间开始'})).toBeVisible()
 await page.getByLabel('宽度',{exact:true}).fill('9');await page.getByLabel('进深',{exact:true}).fill('6')
 await page.getByRole('button',{name:'生成四个平面方案'}).click();await expect(page.locator('.plan-card')).toHaveCount(4)
 await page.screenshot({path:'test-results/gallery.png',fullPage:true})
 await page.locator('.plan-card').first().click()
 const furniture=page.locator('.drawing svg g').first();const b=await furniture.boundingBox();await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+40,b.y+b.height/2+10,{steps:6});await page.mouse.up()
 await page.getByRole('button',{name:'保存平面快照',exact:true}).click()
 const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('insta-studio-v2')));expect(stored.nodes.at(-1).layout.items[0].x).not.toBe(stored.nodes[1].layout.items[0].x)
 await page.getByRole('button',{name:'确认平面并生成白膜'}).click();await expect(page.locator('.model canvas')).toBeVisible();await expect(page.getByRole('alert')).toHaveCount(0)
 await page.screenshot({path:'test-results/white.png',fullPage:true})
 await page.getByLabel('渲染风格').selectOption('both');await page.getByRole('button',{name:'确认白膜，渲染八视角'}).click();await expect(page.locator('.renders img')).toHaveCount(8,{timeout:60000})
 await page.screenshot({path:'test-results/renders.png',fullPage:true})
 const nodes=await page.evaluate(()=>JSON.parse(localStorage.getItem('insta-studio-v2')).nodes);expect(nodes.filter(n=>n.kind==='render')).toHaveLength(2);expect(new Set(nodes.map(n=>n.id)).size).toBe(nodes.length)
 const urls=await page.locator('.renders img').evaluateAll(imgs=>imgs.map(i=>i.src));expect(new Set(urls).size).toBe(8)
 await page.locator('.renders button').first().click();await expect(page.getByRole('link',{name:'下载 PNG'})).toBeVisible();await page.getByRole('button',{name:'关闭',exact:true}).click()
 await page.locator('.branch-list button').filter({hasText:'SI1.0'}).click();await expect(page.locator('.renders img')).toHaveCount(8)
 await page.locator('.branch-list button').filter({hasText:'方案 A'}).click();await page.getByRole('button',{name:'＋ 收银台',exact:true}).click()
 await page.locator('.branch-list button').filter({hasText:'方案 B'}).click();await expect(page.locator('.branch-list button').filter({hasText:'自动保存的调整'})).toHaveCount(1)
 await page.reload();await expect(page.locator('.plan-card')).toHaveCount(4)
 await page.locator('.branch-list button').filter({hasText:'自动保存的调整'}).click();await expect(page.locator('.drawing svg g')).toHaveCount(5)
 expect(errors).toEqual([])
})
test('area-only starts four square plans',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'输入面积',exact:true}).click();await page.getByLabel('面积',{exact:true}).fill('64');await page.getByRole('button',{name:'生成四个平面方案'}).click();await expect(page.locator('.plan-card')).toHaveCount(4);const room=await page.evaluate(()=>JSON.parse(localStorage.getItem('insta-studio-v2')).nodes[0].room);expect(room.w).toBe(8);expect(room.d).toBe(8)})
