import React from "react";
import { Plan } from "../../components/Plan.jsx";
import { catalog } from "../../layout.js";
import { profiles, profileFor } from "../../furniture.js";
import { realAssets } from "../../real-assets.js";
import { createAssetItem, rotateItem } from "../../asset-contract.js";
const uid = () => crypto.randomUUID();
export function EditorStage({ layout, change, selected, setSelected, selectedItem, updatePosition, deleteSelected, warnings, busy, deletedItems, undoDelete, slots, save, white }) {
  return <>{layout.modelAdvice && <p className="hint">实验模型 · {layout.modelAdvice.trainingStores} 家训练门店 · 当前摆放 {layout.modelAdvice.placed} 张体验桌 · {layout.modelAdvice.status === "outside-training-range" ? "超出训练面积，已回退规则" : "位置由规则生成，非模型预测"}</p>}{layout.source && <details className="source-panel" open><summary>图纸来源与待核对项</summary><p>{layout.source.file} · 第 {layout.source.page} 页 · {layout.source.drawing} · {layout.source.date}</p><p>{layout.source.notes}</p><p>来源风格记录：{layout.source.style}；当前几何为参数化草案，非已核实 SKP。</p><div className="source-images"><a href="/references/s03/plan.png" target="_blank" rel="noreferrer"><img src="/references/s03/plan.png" alt="原始家具定位图，点击放大" /></a><img src="/references/s03/effect.png" alt="原PDF效果图参考" /></div></details>}<div className="edit-grid"><div className="drawing"><Plan layout={layout} onChange={change} selected={selected} onSelect={setSelected} /></div><section className="properties"><p className="hint">道具 {layout.items.length} / 200；超限前请导出并分项目管理。</p><h3>参数化示意道具</h3>{Object.entries(catalog).map(([type, item]) => <button key={type} disabled={layout.items.length >= 200} onClick={() => {
    const i = { id: uid(), type, ...item, x: (layout.room.w - item.w) / 2, z: (layout.room.d - item.d) / 2 };
    change([...layout.items, i]);
    setSelected(i.id);
  }}>＋ {item.name}</button>)}<hr /><h3>真实 SU 道具</h3><small>原尺寸 · SI/正面待核；需本地 GLB</small>{realAssets.slice(0,4).map((asset) => <button key={asset.id} disabled={layout.items.length >= 200} onClick={() => {
    const i = createAssetItem(asset, uid(), (layout.room.w - asset.dimensions.w) / 2, (layout.room.d - asset.dimensions.d) / 2);
    change([...layout.items, i]);
    setSelected(i.id);
  }}>＋ {asset.name}</button>)}<small>以上为常用规格；下方“项目工具 → 查看90项资产目录”可检索并加入全部 {realAssets.length} 件已接入模型。</small><hr />{selectedItem ? <><h3>{selectedItem.name}</h3><p>{selectedItem.w} × {selectedItem.d} × {selectedItem.h} m</p>{selectedItem.assetId && <p>资产：{selectedItem.assetId} · 朝向 {selectedItem.rotation || 0}° · SI 未确认</p>}{!selectedItem.assetId && selectedItem.type !== "structure" && <label>道具结构<select aria-label="道具结构" value={profileFor(selectedItem)} onChange={(e) => change(layout.items.map((i) => i.id === selected ? { ...i, profile: e.target.value } : i))}>{Object.entries(profiles).filter(([key]) => key !== "solid").map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><small>参数化示意；构造与厚度待实物核对。</small></label>}{["x", "z"].map((axis) => <label key={axis}>{axis === "x" ? "横向" : "纵向"}位置 / m<input type="number" step=".05" min="0" max={(axis === "x" ? layout.room.w - selectedItem.w : layout.room.d - selectedItem.d).toFixed(2)} value={selectedItem[axis]} onChange={(e) => updatePosition(axis, e.target.valueAsNumber)} /></label>)}<button onClick={() => change(layout.items.map((i) => i.id === selected ? rotateItem(i) : i))}>旋转 90°</button><button onClick={deleteSelected}>删除</button></> : <p>点击道具选中；拖动位置，或输入精确坐标。</p>}<p className={warnings.length ? "warning" : "hint"}>{warnings.length ? warnings.join("；") : "未发现重叠、越界或占用预留通道；消防仍需专项校核"}</p></section></div><p className="hint">撤销删除仅保留当前编辑中的最近 20 次；保存、切换方案或刷新后清空。其他操作请用历史快照恢复。</p><div className="actions"><button disabled={busy || !deletedItems.length || layout.items.length >= 200} onClick={undoDelete}>撤销删除</button><button disabled={slots < 1} onClick={save}>保存平面快照</button><button className="primary" onClick={white} disabled={warnings.length > 0 || slots < 2}>确认平面并生成白膜 →</button></div></>;
}
