function validate(rows){if(rows.length<3||new Set(rows.map(r=>r.id)).size!==rows.length)throw Error('Need at least three unique stores');for(const r of rows)if(!Number.isFinite(r.areaM2)||r.areaM2<=0||!Number.isFinite(r.tableCount)||r.tableCount<0)throw Error('Invalid training row')}
export function fit(rows,{lambda=.1,steps=3000,lr=.05}={}){
 validate(rows);const mean=rows.reduce((s,r)=>s+r.areaM2,0)/rows.length;const scale=Math.sqrt(rows.reduce((s,r)=>s+(r.areaM2-mean)**2,0)/rows.length)||1;
 let b=0,w=0;const history=[];
 for(let k=0;k<steps;k++){let db=0,dw=0,loss=0;for(const r of rows){const x=(r.areaM2-mean)/scale,e=b+w*x-r.tableCount;db+=2*e/rows.length;dw+=2*e*x/rows.length;loss+=e*e/rows.length}dw+=2*lambda*w;loss+=lambda*w*w;b-=lr*db;w-=lr*dw;if(k%100===0||k===steps-1)history.push({step:k,loss});}
 return {version:1,algorithm:'standardized-area ridge regression / gradient descent',target:'product demonstration island table count; excludes cashier and unboxing',mean,scale,b,w,lambda,steps,lr,history,trainIds:rows.map(r=>r.id),minArea:Math.min(...rows.map(r=>r.areaM2)),maxArea:Math.max(...rows.map(r=>r.areaM2)),status:'experimental',features:['areaM2']};
}
export function predict(model,area,{allowExtrapolation=false}={}){if(!Number.isFinite(area)||area<=0)throw Error('Area must be positive');if(!allowExtrapolation&&(area<model.minArea||area>model.maxArea))throw Error('Outside training area');return model.b+model.w*(area-model.mean)/model.scale}
export function evaluate(rows){validate(rows);const folds=rows.map(row=>{const train=rows.filter(r=>r.id!==row.id),model=fit(train),p=predict(model,row.areaM2,{allowExtrapolation:true}),baseline=train.reduce((s,r)=>s+r.tableCount,0)/train.length;return {testId:row.id,trainIds:model.trainIds,actual:row.tableCount,predicted:p,baseline,absoluteError:Math.abs(p-row.tableCount),baselineError:Math.abs(baseline-row.tableCount),outsideFoldRange:row.areaM2<model.minArea||row.areaM2>model.maxArea}});return {method:'leave-one-store-out; standardization fit inside each fold; lambda fixed before evaluation',folds,mae:folds.reduce((s,f)=>s+f.absoluteError,0)/folds.length,meanBaselineMAE:folds.reduce((s,f)=>s+f.baselineError,0)/folds.length,roundedAccuracy:folds.filter(f=>Math.round(f.predicted)===f.actual).length/folds.length,warning:'Very small sample; no independent final test set; not a generalization guarantee'}}
