import fs from 'node:fs/promises';
const root=new URL('../../',import.meta.url),out=new URL('资源库/99_历史归档/训练实验/layout-v0/',root);await fs.mkdir(out,{recursive:true});
const manifests=JSON.parse(await fs.readFile(new URL('资源库/99_历史归档/训练候选/batch01/manifest.json',root),'utf8'));
// Counts visually checked against selected furniture plans; cash/unboxing excluded.
const labels={'PDF-159':[68.3,3],'PDF-160':[20.3,1],'PDF-194':[21,2],'PDF-051':[16,2],'PDF-171':[19.5,1],'PDF-239':[19.1,2],'PDF-079':[141.5,4],'PDF-083':[48,3],'PDF-071':[38,2],'PDF-417':[null,3],'PDF-293':[12,2],'PDF-296':[24,2]};
const rows=manifests.map(m=>({id:m.id,file:m.file,tag:m.tag,areaM2:labels[m.id][0],tableCount:labels[m.id][1],sourceSha256:m.sourceSha256,page:m.assets.find(a=>a.role==='plan').page,areaEvidence:labels[m.id][0]===null?'No explicit area transcribed; exclude from area model':'PDF printed area (not usable floor area)',countEvidence:'Visual count of product island tables; excludes unboxing/cashier/workshop tables',annotationStatus:'agent-reviewed, awaiting designer review',trainingEligible:labels[m.id][0]!==null}));
await fs.writeFile(new URL('labels.json',out),JSON.stringify(rows,null,2));
// Draft measurements explicitly separated from training targets. x/z top-left in metres.
const geometry=[
 {id:'PDF-051',room:{w:6.7,d:2.4},outline:[[0,0],[6.7,0],[6.7,2.4],[0,2.4]],openEdges:['front','left','right'],dimensionEvidence:['overall 6700mm','overall 2400mm','table 1800 × 1000mm'],objects:[['table',.08,1.4,1.8,1,.9],['table',3.08,1.4,1.8,1,.9],['display',0,.15,1.55,.5,1.3],['display',5.15,.15,1.55,.5,1.3],['counter',1.55,.15,1.8,.5,.9],['unbox',3.35,.15,1.8,.5,.9]],obstacles:[],notes:'Side columns are outside the 6700mm lot and not dimensioned; rear low wall height1600mm. Cabinet positions follow dimension chain.'},
 {id:'PDF-296',room:{w:6,d:4},outline:[[0,0],[6,0],[6,4],[0,4]],openEdges:['front','left'],dimensionEvidence:['overall 6000mm','overall 4000mm','table1800 × 800mm'],objects:[['table',.9,.7,1.8,.8,.9],['table',.9,2.5,1.8,.8,.9],['counter',4.12,1.68,.6,1.8,.9],['display',3.98,.22,1.6,.46,2.4]],obstacles:[{kind:'frame-foot',box:[.08,.08,.2,.2],status:'draft estimate'},{kind:'frame-foot',box:[.08,3.72,.6,.2],status:'draft estimate'}],notes:'Table dimensions explicit; positions/counter/display origins approximate from dimension chains; frame/side display zones incomplete.'},
 {id:'PDF-194',room:{w:4.7,d:null},outline:null,openEdges:['front'],dimensionEvidence:['upper width4700mm','table1800 × 1000mm','depth chains use different reference edges; unresolved'],objects:[['table',null,null,1,1.8,null],['table',null,null,1,1.8,null]],obstacles:[],notes:'Do not force depth from area/width. Retain unresolved coordinate origin; not ready for layout reconstruction.'},
 {id:'PDF-083',room:{w:5.255,d:9.133},outline:null,openEdges:['front'],dimensionEvidence:['upper width5255mm','left depth9133mm','slanted front edge','islands1800mm and height900mm'],objects:[['table',null,null,1.8,null,.9],['table',null,null,1.8,null,.9],['table',null,null,1.8,null,.9]],obstacles:[{kind:'column',box:null,status:'two right-edge columns need coordinates'}],notes:'Bounding dimensions only; store has slanted front, rear storage and right columns. Must not replace with filled rectangle.'}
];
for(const g of geometry){const s=rows.find(r=>r.id===g.id);g.source={file:s.file,page:s.page,sha256:s.sourceSha256};g.units='m';g.coordinateSystem='x right, z down from drawing top-left; exact origin unresolved where noted';g.status='draft, not construction-ready';g.geometryTrainingEligible=false;g.objects=g.objects.map(([kind,x,z,w,d,h],i)=>({id:g.id+'-'+i,kind,x,z,w,d,h,rotation:0,confidence:x===null?'dimensions-only':'dimension-chain/visual draft'}));}
await fs.writeFile(new URL('geometry-drafts.json',out),JSON.stringify(geometry,null,2));console.log('12 count annotations (11 area targets); 4 geometry drafts, 2 partially dimensioned');
